services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-80}:80'
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - ./:/var/www/html

  mysql:
    image: 'mysql:8.0'
    volumes:
      - portfolio-db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: portfolio-db

volumes:
  portfolio-db-data:
