version: '3.8'

services:
  app:
    build: .
    image: laravel-custom:latest
    container_name: laravel_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - mysql
    working_dir: /var/www/html
    command: >
      bash -c "
        until mysqladmin ping -h'mysql' --silent; do
          echo 'Waiting for MySQL...';
          sleep 2;
        done &&
        composer install &&
        php artisan config:clear &&
        if [ ! -f .env ]; then cp .env.example .env && php artisan key:generate; fi &&
        php artisan migrate &&
        chmod -R 775 storage bootstrap/cache &&
        chown -R www-data:www-data storage bootstrap/cache &&
        apache2-foreground
      "

  mysql:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: portfolio-db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpass
    volumes:
      - portfolio-db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: laravel_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: laravel
      PMA_PASSWORD: laravelpass
    depends_on:
      - mysql

volumes:
  portfolio-db-data:
